#!/usr/bin/env python3
"""
FloatTrip AMap POI filter.

Read the candidate pool generated by tools/place_candidate_pool.py, verify each
candidate with AMap keyword POI search, and keep only real attraction-like POIs.

Examples:
  python3 tools/place_candidate_pool.py 南京 --days 3 --json > /tmp/candidates.json
  python3 tools/amap_poi_filter.py /tmp/candidates.json --json
  python3 tools/amap_poi_filter.py /tmp/candidates.json --city 南京 --json
  python3 tools/amap_poi_filter.py /tmp/candidates.json --min-mentions 3 --json
  python3 tools/amap_poi_filter.py /tmp/candidates.json --names-json
  python3 tools/amap_poi_filter.py /tmp/candidates.json --names
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "FloatTripAmapPoiFilter/0.1"
)
LOCAL_ENV_FILE = Path(__file__).resolve().parents[1] / ".env.local"
AMAP_TEXT_SEARCH_URL = "https://restapi.amap.com/v3/place/text"

ATTRACTION_TYPE_KEYWORDS = (
    "风景名胜",
    "公园广场",
    "博物馆",
    "展览馆",
    "美术馆",
    "科技馆",
    "纪念馆",
    "寺庙",
    "道观",
    "教堂",
    "文化宫",
    "文物古迹",
    "动物园",
    "植物园",
    "水族馆",
    "海洋馆",
    "游乐场",
    "主题乐园",
    "度假区",
    "自然地名",
)

BLOCKED_TYPE_KEYWORDS = (
    "住宿服务",
    "餐饮服务",
    "购物服务",
    "生活服务",
    "公司企业",
    "商务住宅",
    "金融保险",
    "汽车服务",
    "汽车维修",
    "摩托车服务",
    "医疗保健",
    "政府机构",
    "科教文化服务;学校",
    "交通设施服务",
    "道路附属设施",
)


def load_local_env() -> None:
    if not LOCAL_ENV_FILE.exists():
        return
    for line in LOCAL_ENV_FILE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key and key not in os.environ:
            os.environ[key] = value


def require_amap_key() -> str:
    api_key = os.getenv("AMAP_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("缺少 AMAP_API_KEY。请在环境变量或 .env.local 中配置高德 Web服务 Key 后重试。")
    return api_key


def http_get_json(url: str, timeout: int = 15) -> dict[str, Any]:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": USER_AGENT,
            "Accept": "application/json,*/*;q=0.8",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.7",
        },
    )
    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                charset = response.headers.get_content_charset() or "utf-8"
                return json.loads(response.read().decode(charset, errors="replace"))
        except Exception as exc:
            last_error = exc
            time.sleep(0.8 * (attempt + 1))
    raise RuntimeError(f"请求失败：{redact_url(url)}；原因：{last_error}")


def redact_url(url: str) -> str:
    parsed = urllib.parse.urlparse(url)
    query = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
    for secret_key in ("key", "api_key", "access_token", "token"):
        if secret_key in query:
            query[secret_key] = ["<redacted>"]
    redacted_query = urllib.parse.urlencode(query, doseq=True)
    return urllib.parse.urlunparse(parsed._replace(query=redacted_query))


def load_candidate_payload(path: str) -> dict[str, Any]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError("候选池文件必须是 JSON object")
    if not isinstance(payload.get("candidate_pool"), list):
        raise RuntimeError("候选池文件缺少 candidate_pool 数组")
    return payload


def search_amap_pois(keyword: str, admin_region: str, api_key: str, offset: int) -> list[dict[str, Any]]:
    params = {
        "key": api_key,
        "keywords": keyword,
        "city": admin_region,
        "citylimit": "true",
        "offset": str(offset),
        "page": "1",
        "extensions": "all",
        "output": "json",
    }
    url = f"{AMAP_TEXT_SEARCH_URL}?{urllib.parse.urlencode(params)}"
    data = http_get_json(url)
    if data.get("status") != "1":
        info = data.get("info") or "未知错误"
        raise RuntimeError(f"高德 POI 搜索失败：{info}")
    pois = data.get("pois", [])
    return pois if isinstance(pois, list) else []


def choose_attraction_poi(
    candidate_name: str,
    pois: list[dict[str, Any]],
    admin_region: str,
) -> dict[str, Any] | None:
    best_poi: dict[str, Any] | None = None
    best_score = -1
    for poi in pois:
        if not isinstance(poi, dict):
            continue
        poi_type = str(poi.get("type", ""))
        poi_name = str(poi.get("name", ""))
        if not is_attraction_type(poi_type) or not is_in_admin_region(poi, admin_region):
            continue
        score = match_score(candidate_name, poi_name, poi_type)
        if score > best_score:
            best_score = score
            best_poi = poi
    return best_poi


def is_in_admin_region(poi: dict[str, Any], admin_region: str) -> bool:
    """Verify a POI belongs to the requested AMap administrative region."""
    region = admin_region.strip()
    if not region:
        return False

    adcode = str(poi.get("adcode", "")).strip()
    if re.fullmatch(r"\d{6}", region):
        return adcode_matches_region(adcode, region)

    expected_name = normalize_region_name(region)
    poi_region_names = (
        poi.get("pname", ""),
        poi.get("cityname", ""),
        poi.get("adname", ""),
    )
    return any(
        normalize_region_name(str(name)) == expected_name
        for name in poi_region_names
        if name
    )


def adcode_matches_region(poi_adcode: str, region_adcode: str) -> bool:
    if not re.fullmatch(r"\d{6}", poi_adcode):
        return False
    if region_adcode.endswith("0000"):
        return poi_adcode[:2] == region_adcode[:2]
    if region_adcode.endswith("00"):
        return poi_adcode[:4] == region_adcode[:4]
    return poi_adcode == region_adcode


def normalize_region_name(region: str) -> str:
    normalized = region.strip()
    for suffix in ("特别行政区", "自治州", "自治区", "省", "市", "区", "县"):
        if normalized.endswith(suffix):
            return normalized[: -len(suffix)]
    return normalized


def is_attraction_type(poi_type: str) -> bool:
    if not poi_type:
        return False
    if any(blocked in poi_type for blocked in BLOCKED_TYPE_KEYWORDS):
        return False
    return any(keyword in poi_type for keyword in ATTRACTION_TYPE_KEYWORDS)


def match_score(candidate_name: str, poi_name: str, poi_type: str) -> int:
    score = 0
    if candidate_name == poi_name:
        score += 100
    elif candidate_name in poi_name or poi_name in candidate_name:
        score += 70
    else:
        score += common_char_score(candidate_name, poi_name)

    if "风景名胜" in poi_type:
        score += 20
    if any(keyword in poi_type for keyword in ("博物馆", "纪念馆", "公园广场", "文物古迹")):
        score += 12
    return score


def common_char_score(left: str, right: str) -> int:
    left_chars = {char for char in left if is_meaningful_char(char)}
    right_chars = {char for char in right if is_meaningful_char(char)}
    if not left_chars or not right_chars:
        return 0
    return int(40 * len(left_chars & right_chars) / len(left_chars | right_chars))


def is_meaningful_char(char: str) -> bool:
    return bool(re.match(r"[\u4e00-\u9fa5A-Za-z0-9]", char))


def parse_location(value: Any) -> dict[str, float] | None:
    if not isinstance(value, str) or "," not in value:
        return None
    lng_text, lat_text = value.split(",", 1)
    try:
        return {"lng": float(lng_text), "lat": float(lat_text)}
    except ValueError:
        return None


def normalize_poi(poi: dict[str, Any]) -> dict[str, Any]:
    normalized = {
        "provider": "amap",
        "id": str(poi.get("id", "")),
        "name": str(poi.get("name", "")),
        "type": str(poi.get("type", "")),
        "adcode": str(poi.get("adcode", "")),
        "province": str(poi.get("pname", "")),
        "city": str(poi.get("cityname", "")),
        "district": str(poi.get("adname", "")),
        "address": normalize_address(poi.get("address")),
        "location": parse_location(poi.get("location")),
    }
    return {key: value for key, value in normalized.items() if value not in ("", None, [])}


def normalize_address(value: Any) -> str:
    if isinstance(value, list):
        return " ".join(str(item) for item in value if item)
    return str(value or "")


def filter_candidate_pool(
    payload: dict[str, Any],
    admin_region: str,
    api_key: str,
    offset: int,
    min_mentions: int,
) -> dict[str, Any]:
    filtered_candidates: list[dict[str, Any]] = []
    candidate_pool = payload.get("candidate_pool", [])
    if not isinstance(candidate_pool, list):
        raise RuntimeError("candidate_pool 必须是数组")
    frequency_candidates = [
        candidate
        for candidate in candidate_pool
        if isinstance(candidate, dict) and int(candidate.get("mention_count", 0)) >= min_mentions
    ]

    for candidate in frequency_candidates:
        if not isinstance(candidate, dict):
            continue
        name = str(candidate.get("name", "")).strip()
        if not name:
            continue
        try:
            pois = search_amap_pois(name, admin_region, api_key, offset)
        except Exception as exc:
            print(f"[warn] 高德 POI 校验失败：name={name!r}；{exc}", file=sys.stderr)
            continue

        poi = choose_attraction_poi(name, pois, admin_region)
        if not poi:
            continue

        enriched = dict(candidate)
        enriched["name"] = str(poi.get("name") or name)
        enriched["poi"] = normalize_poi(poi)
        filtered_candidates.append(enriched)
        time.sleep(0.25)

    output = dict(payload)
    output["candidate_pool"] = dedupe_by_poi(filtered_candidates)
    output["filter"] = {
        "provider": "amap",
        "admin_region": admin_region,
        "min_mentions": min_mentions,
        "kept_count": len(output["candidate_pool"]),
        "input_count": len(candidate_pool),
        "frequency_kept_count": len(frequency_candidates),
        "frequency_filtered_count": len(candidate_pool) - len(frequency_candidates),
    }
    return output


def dedupe_by_poi(candidates: list[dict[str, Any]]) -> list[dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    for candidate in candidates:
        poi = candidate.get("poi")
        poi_id = poi.get("id") if isinstance(poi, dict) else ""
        key = str(poi_id or candidate.get("name", ""))
        if not key:
            continue
        existing = merged.get(key)
        if not existing:
            merged[key] = candidate
            continue
        existing["mention_count"] = int(existing.get("mention_count", 0)) + int(candidate.get("mention_count", 0))
        existing["score"] = int(existing.get("score", 0)) + int(candidate.get("score", 0))
        existing_sources = existing.setdefault("sources", [])
        for source in candidate.get("sources", []):
            if source not in existing_sources:
                existing_sources.append(source)

    return sorted(merged.values(), key=lambda item: (-int(item.get("score", 0)), str(item.get("name", ""))))


def print_human_report(output: dict[str, Any]) -> None:
    destination = output.get("destination", "")
    candidates = output.get("candidate_pool", [])
    filter_meta = output.get("filter", {})
    print(f"\nFloatTrip 高德 POI 景点过滤：{destination}")
    if isinstance(filter_meta, dict):
        print(f"输入 {filter_meta.get('input_count', 0)} 个，保留 {filter_meta.get('kept_count', 0)} 个\n")
    for candidate in candidates[:30] if isinstance(candidates, list) else []:
        poi = candidate.get("poi", {}) if isinstance(candidate, dict) else {}
        poi_type = poi.get("type", "") if isinstance(poi, dict) else ""
        print(
            f"- {candidate.get('name')}｜score={candidate.get('score')}｜"
            f"出现 {candidate.get('mention_count')} 次｜{poi_type}"
        )


def extract_candidate_names(output: dict[str, Any]) -> list[str]:
    candidates = output.get("candidate_pool", [])
    if not isinstance(candidates, list):
        return []
    return [str(candidate.get("name", "")) for candidate in candidates if isinstance(candidate, dict) and candidate.get("name")]


def print_candidate_names(output: dict[str, Any]) -> None:
    for name in extract_candidate_names(output):
        print(name)


def main() -> int:
    load_local_env()

    parser = argparse.ArgumentParser(description="使用高德 POI 校验并过滤候选景点池。")
    parser.add_argument("candidate_json", help="place_candidate_pool.py 输出的 JSON 文件路径")
    parser.add_argument("--city", default="", help="高德搜索行政区；兼容旧参数，优先使用 --admin-region")
    parser.add_argument(
        "--admin-region",
        default="",
        help="要求 POI 所属的高德行政区名称或 adcode；默认使用 --city 或输入 JSON 的 destination",
    )
    parser.add_argument("--offset", type=int, default=5, help="每个候选名最多取几个高德 POI，默认 5")
    parser.add_argument("--min-mentions", type=int, default=1, help="最小出现次数，默认 1")
    parser.add_argument("--json", action="store_true", help="输出 JSON")
    parser.add_argument("--names-json", action="store_true", help="只输出过滤后的景点名称 JSON 数组")
    parser.add_argument("--names", action="store_true", help="只按降序逐行输出过滤后的景点名称")
    args = parser.parse_args()

    try:
        payload = load_candidate_payload(args.candidate_json)
        admin_region = (
            args.admin_region
            or args.city
            or str(payload.get("destination", "")).strip()
        )
        if not admin_region:
            raise RuntimeError(
                "缺少行政区信息。请在输入 JSON 中提供 destination，或使用 --admin-region 指定。"
            )
        output = filter_candidate_pool(
            payload,
            admin_region,
            require_amap_key(),
            args.offset,
            args.min_mentions,
        )
    except Exception as exc:
        print(f"高德 POI 景点过滤失败：{exc}", file=sys.stderr)
        return 1

    if args.names:
        print_candidate_names(output)
    elif args.names_json:
        print(json.dumps(extract_candidate_names(output), ensure_ascii=False, indent=2))
    elif args.json:
        print(json.dumps(output, ensure_ascii=False, indent=2))
    else:
        print_human_report(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
